# Generated by Django 4.2.24 on 2025-10-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='construction.jpg', upload_to='posts/'),
        ),
    ]
