# Generated by Django 4.2.24 on 2025-10-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
